# -*- coding: utf-8 -*-
"""example.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAQd26CE4dtTnwz8XoIh-VdTKZGVq8c-
"""

import pandas as pd
# Assume PensionValuation and PensionForecaster classes are in these files
from pension_valuation import PensionValuation
from pension_forecaster import PensionForecaster

# 1. Define all plan, actuarial, and simulation assumptions
plan_parameters = { ... }
simulation_profile = { ... }

# 2. Load initial data
mortality_table = pd.read_excel('mortality_df.xlsx')
initial_census = { 'actives': initial_actives_df, ... }

# 3. Instantiate the valuation engine
valuation_engine = PensionValuation(
    interest_rate=0.05,
    salary_growth_rate=0.03,
    mortality_df=mortality_table,
    other_decrements={'withdrawal': "max(0, 0.10 - 0.005 * (age - 25))"}
)

# 4. Instantiate the forecaster, passing the valuation engine as a tool
forecaster = PensionForecaster(
    plan_parameters=plan_parameters,
    simulation_profile=simulation_profile,
    valuation_engine=valuation_engine,
    initial_census_dfs=initial_census,
    initial_assets=800000.0,
    valuation_method='puc'
)

# 5. Run the forecast
results_df = forecaster.run_forecast(projection_years=50)
print(results_df)